### ISSUE TITLE
Do you have a template without ts?

### ISSUE THREAD

**Issue by ghost** [alessandropisu/vite-react-ts-minimal-template#1]

**Comment by alessandropisu** [comment]
Hey there, unfortunately nope but I think you can easily change this template and make it for JS by:
- Rename all .**ts/.tsx** files in **.js** extension
- Remove **tsconfig** files
- Remove ESLint rules for TypeScript such **airbnb-typescript** or **@typescript-eslint** and change the default parser

You can also use [the official React Vite template](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-react) as guideline to adapt it :)

**Comment by ghost** [comment]
Ah thanks man, already done 👍
